CREATE TABLE `sri_krishna_stock` (
 `id` int(100) NOT NULL AUTO_INCREMENT,
 `created_date_time` mediumtext NOT NULL,
 `creator` mediumtext NOT NULL,
 `creator_name` mediumtext NOT NULL,
 `bill_company_id` mediumtext NOT NULL,
 `stock_date` date NOT NULL,
 `supplier_id` mediumtext NOT NULL,
 `supplier_name` mediumtext NOT NULL,
 `factory_id` mediumtext NOT NULL,
 `factory_name` mediumtext NOT NULL,
 `godown_id` mediumtext NOT NULL,
 `godown_name` mediumtext NOT NULL,
 `size_id` mediumtext NOT NULL,
 `size_name` mediumtext NOT NULL,
 `gsm_id` mediumtext NOT NULL,
 `gsm_name` mediumtext NOT NULL,
 `bf_id` mediumtext NOT NULL,
 `bf_name` mediumtext NOT NULL,
 `inward_unit` mediumtext NOT NULL,
 `outward_unit` mediumtext NOT NULL,
 `stock_type` mediumtext NOT NULL,
 `stock_action` mediumtext NOT NULL,
 `bill_unique_id` mediumtext NOT NULL,
 `bill_unique_number` mediumtext NOT NULL,
 `remarks` mediumtext NOT NULL,
 `deleted` int(100) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;